### ISSUE TITLE
[FEATURE] Nada.bot Search Users 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#1]
# Problem
Can't search other users whether they are human verified
# User Story(s):
 As a user, I want to search the score of other users, so that I can see what stamps they have verified, or that they havent and havent verfied, or whether they are human.

# Description
Search all account 
# Acceptance Criteria

# Limitations 
- maybe hard to index every stamp by users to know how to globally search
- can you search anyone by account id even if they dont have stamp (are we just searching all counts that exists?
# Resources
- Check whether account is human https://github.com/PotLock/core/blob/main/contracts/sybil/src/human.rs
-

**Comment by codingshot** [comment]
error validation on search, and it defaults ot human

**Comment by wpdas** [comment]
> error validation on search, and it defaults ot human

This is an issue within the contract. cc @lachlanglen . Please take a look at the image below. **pipico.near**
 doesn't exist yet on mainnet, even though it's returning `is_human: true`.

![Image](https://github.com/PotLock/nadabot-app/assets/3761994/2c908a98-c7d8-4bea-9cf5-89c9ef71dc09)

**Comment by wpdas** [comment]
Fixed: Human Threshold was set to 20.
