### ISSUE TITLE
[ENHANCE] Open Contracts and Address referneeces in nearblock 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#12]
# Summary

[Brief overview of the enhancement and why it is needed or desired]

# Description

[Detailed description of the enhancement, including how it would work and any design considerations]

# Acceptance Criteria

[List of criteria that must be met for the enhancement to be considered accepted]

# Additional Information

[Any other relevant information, such as links to related issues or pull requests]

**Comment by wpdas** [comment]
Done
