### ISSUE TITLE
[ENHANCE] Popup overlay shadow clipped

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#13]
# Summary

THe gray overlay is only showing up for frame not for whole page, so looks off when scrolling

To reproduce click on stamp #8 also related to this
<img width="1331" alt="" src="https://github.com/PotLock/nadabot-app/assets/45281667/3fda8524-57f0-44fa-aa58-fbabd376fce0">

# Acceptance Criteria

- [x] quick overlay

# Additional Information

**Comment by wpdas** [comment]
done
