### ISSUE TITLE
[FEATURE] Search Stamps 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#14]
# Problem
Cannot currently search stamps
# User Story(s):
 As a _______, I want to ____, so that I can

# Description
Description of solution

# Acceptance Criteria

- [x] search stamps by name
- [x] search stamps by deploers

# Limitations 
Outline any potential limitations
# Resources
- outline links and relevant resources, references implementations

**Comment by wpdas** [comment]
It's currently searching by contract's name, contract's address and by contract's deployer
