### ISSUE TITLE
[FEATURE] Filter Stamps 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#15]
# Problem
Explain the problem in details

# User Story(s):
 As a _______, I want to ____, so that I can

# Description
Description of solution

# Acceptance Criteria

- [x] filter stamps by points
- [x] filter stamps by most recently aded
- [x] filter stamps by need to verify 

# Limitations 
Outline any potential limitations
# Resources
- outline links and relevant resources, references implementations

**Comment by wpdas** [comment]
Done
