### ISSUE TITLE
[ENHANCE] Tooltip on what stamp is for add stamp 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#16]
# Summary

Need to add copy. Add tool tipf or stamp so with popup so we cna go to docs in new tab. Their is no design for this currently 

![Image](https://github.com/PotLock/nadabot-app/assets/45281667/5cb3c66b-a66c-43b5-878a-e84137ae0a8f)

**Comment by wpdas** [comment]
Done
