### ISSUE TITLE
[FEATURE] Staging,Testnet Prod 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#17]
# Problem
devleopers and users need staging testnet and prod

already configured on deployment, just need to config env and have contracts deployed

**Comment by lachlanglen** [comment]
@wpdas @codingshot is there anything remaining for this to be considered complete?

**Comment by wpdas** [comment]
> @wpdas @codingshot is there anything remaining for this to be considered complete?

Nope, I believe we're good to close this.
