### ISSUE TITLE
[ENHANCE] Add environment indicator when using staging or testnet env

### ISSUE THREAD

**Issue by lachlanglen** [PotLock/nadabot-app#19]
# Summary

As a User, I want to be aware if I am using the `staging` or `testnet` environment.

# Description

Can be basic, just need a clear indication that you are on staging or testnet. Could be a banner unless that is too obtrusive.

# Acceptance Criteria

- [x] Displays environment name to user when on `staging` or `testnet`

# Additional Information

**Comment by wpdas** [comment]
Done. This is showing the network for staging and testnet only.
