### ISSUE TITLE
[FEATURE] Pull Icons from NEAR Social Profile 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#2]
# Problem
Currently icon preview is blank, prefer it pulled from NEAR Social Profile iamge
# User Story(s):
 As a user, I want to see whether account have a near social profile iamge, so that I can recognize them more easily. 

# Description
Pull social profile image from enar socail
# Acceptance Criteria
-
- [x] if they have image pull it and show in proifle dropdown
- [x] show on user search drop down #1 

# Limitations 
- may need to use social indexer
# Resources
-  ADD FIGMA

**Comment by wpdas** [comment]
It's pulling the image from Near Social. If there's no profile image, it's going to show only the first letter of the user's name/account-id
