### ISSUE TITLE
[ENHANCE] Add Stamp Copy

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#20]
add copy for submit stamp  -stamp description

A stamp is a smart-contract enabled check on NEAR to be added to the nadabot sybil registry, to verify something about an account whether it be a role, identity, proof of ownership, or behavior.  

with a info tip to open up in docs https://docs.nada.bot/guides/for-sybil-providers

**Comment by wpdas** [comment]
Done
