### ISSUE TITLE
[BUG] Convert gas from Tgas when registering or updating provider

### ISSUE THREAD

**Issue by lachlanglen** [PotLock/nadabot-app#27]
**Describe the bug**
If a registrant enters 100 Tgas units for their provider, this should be converted to indivisible gas units before being sent to the contract. You can do this by multiplying Tgas units by 10^12.

Additionally, please validate that Tgas is not greater than max allowed (100 Tgas units, or `100 * 10**12` gas - this limit is implemented on contract) - this also a part of [this ticket](https://github.com/PotLock/nadabot-app/issues/28), just adding here for awareness.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wpdas** [comment]
Done. May be you wanna review this @lachlanglen ? If not, we can move to done. It was deployed to all envs.

**Comment by lachlanglen** [comment]
Yes will check

**Comment by lachlanglen** [comment]
@wpdas can the account_id_arg_name input value default to "account_id", not just a placeholder?

**Comment by lachlanglen** [comment]
looks great, thanks
