### ISSUE TITLE
[ENHANCE] Validate form inputs according to on-chain constraints

### ISSUE THREAD

**Issue by lachlanglen** [PotLock/nadabot-app#28]
# Summary

See https://github.com/PotLock/core/tree/main/contracts/sybil#constants--input-validation for on-chain constraints

# Description

[Detailed description of the enhancement, including how it would work and any design considerations]

# Acceptance Criteria

[List of criteria that must be met for the enhancement to be considered accepted]

# Additional Information

[Any other relevant information, such as links to related issues or pull requests]

**Comment by wpdas** [comment]
Done.
