### ISSUE TITLE
[FEATURE] Configure Application with Deployed Contract

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#3]
# Problem
Configure application with deployed contract. Currently on testnet
# User Story(s):
 As a sybil provder, I want to have a deployed contract, so that I can add my contract to mainnet

# Description
Update with mainnet contract. 
# Acceptance Criteria

- [x] deployed on production branch

# Limitations 
- need to deploy contract and blocked on this on core
# Resources

**Comment by wpdas** [comment]
done
