### ISSUE TITLE
[ENHANCE] Lag on admin slider 🟠

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#30]
Slight lag on admin slider, shows loading screen

**Comment by lachlanglen** [comment]
@codingshot is this ready? why 🟠

**Comment by wpdas** [comment]
@codingshot this is intentional. There's a debounced (waits for a few seconds) before calling the contract's method to update that value. Otherwise, it would call the method and show the loading as soon as you change the slider position.

**Comment by wpdas** [comment]
Done. Deployed to testnet. I'll close this after deploying to staging and prod (mainnet)

**Comment by wpdas** [comment]
Done
