### ISSUE TITLE
[BUG] Admins Show As Human With No Stamps

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#32]
**Describe the bug**
Should show as not a human with no stamps for admin in top right corner
**To Reproduce**
- login as admin
- show correctly human state based on huamn threshold

![Image](https://github.com/PotLock/nadabot-app/assets/45281667/3ff8fa8f-f62a-48ed-a4d6-8c57319d29dc)

**Comment by wpdas** [comment]
@codingshot  This is also intentional. It was mentioned before that every admin is a verified human automatically. But I can change this.

**Comment by wpdas** [comment]
Done
