### ISSUE TITLE
[BUG] User Not Staying Logged in

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#33]
**Describe the bug**
Not stayling logged in or showing profile iamge
**To Reproduce**
1. login (was using meteor wallet)
2. refresh page
3. not showing logged in and needed to keep signin in and adding access key

**Expected behavior**
Continue styaing logged in when refreshed.
**Screenshots**

![Image](https://github.com/PotLock/nadabot-app/assets/45281667/71ba569b-9866-4e3e-b977-39967df8651f)

**Comment by wpdas** [comment]
Done. Deployed to testnet. I'll close this after deploying to staging and prod (mainnet)

**Comment by wpdas** [comment]
Done
