### ISSUE TITLE
show how much point is needed for user to be considered Human Verified.(or fix bug if the current UI is correct)[ENHANCE]

### ISSUE THREAD

**Issue by Prometheo** [PotLock/nadabot-app#35]
# Summary

[Brief overview of the enhancement and why it is needed or desired]
the current ui just says to keep collecting stamp points but has a misleading stat as shown in the mage below, 22/20 points which suggests that 20 points is needed? but then still says user is not verified despite having more

# Description
[Detailed description of the enhancement, including how it would work and any design considerations]
![photo_2024-02-06_13-22-23](https://github.com/PotLock/nadabot-app/assets/40220495/071d04a6-36a6-4730-bd8f-fc7374e60375)

# Acceptance Criteria

[List of criteria that must be met for the enhancement to be considered accepted]

# Additional Information

[Any other relevant information, such as links to related issues or pull requests]

**Comment by codingshot** [comment]
#36 related to this
