### ISSUE TITLE
[BUG] Not Adding Up All Points Correctly

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#36]
**Describe the bug**
"Points are wrongly calculated imo (says 23 but I should have 70) and it says that I'm not considered as a human meanwhile I see a stamp "verified human""
**To Reproduce**
This maybe because already meets human amount

**Expected behavior**
points to show totla number of points

**Screenshots**

![Image](https://github.com/PotLock/next-app/assets/45281667/08db9530-f88a-4671-9276-172d7c611254)

![Image](https://github.com/PotLock/next-app/assets/45281667/b74a2f70-cdb4-479c-947e-0d17a3740d12)

**Additional context**
crans.near

**Comment by wpdas** [comment]
@codingshot the copy for description is wrong but the score is correct. The calc is an avarage of **(sum amount of checks) / total checks**.

**Comment by lachlanglen** [comment]
The score should be the total score (not the average)

**Comment by wpdas** [comment]
Right. I'll change it.

**Comment by KazanderDad** [comment]
![Screenshot 2024-02-12 23 10 44](https://github.com/PotLock/nadabot-app/assets/98373366/20dcf17a-82cb-4806-9482-b1f591228636)

**Comment by KazanderDad** [comment]
Still looking at an average. Pls make me human.

**Comment by KazanderDad** [comment]
![image](https://github.com/PotLock/nadabot-app/assets/98373366/fe01b037-5687-4f00-9301-7b46024d955b)

Looks a lot better. Many thanks!!
