### ISSUE TITLE
Seperate Verify in Itw Owns Section: Updates on the flow, optimisation of the states

### ISSUE THREAD

**Issue by KriTiCal007** [PotLock/nadabot-app#37]
# Summary
1) Separated Verify from Get check
2) Minimized the Scroll by moving the searchbar to NAV
3) Null state for recent checks
4) The Completed check card is bit changed
<img width="641" alt="image" src="https://github.com/PotLock/nadabot-app/assets/56259533/e30b067d-ed63-416e-a667-f09971ff006a">
![Uploading image.png…]()

# Description
The main issue is separating the verify and get check cards so I have made updates on the cards. Secondaly to reduce the scroll the search bar is sent to the navbar. Check figma in the link below
https://www.figma.com/file/ckixqGfuRKZ63tTvdJzi6j/Potlock?type=design&node-id=7882-31292&mode=dev
[Detailed description of the enhancement, including how it would work and any design considerations]

# Acceptance Criteria

# Additional Information

[Any other relevant information, such as links to related issues or pull requests]
<img width="606" alt="image" src="https://github.com/PotLock/nadabot-app/assets/56259533/31a025c5-9d44-4fe8-b1de-984d6998e46c">

**Comment by wpdas** [comment]
Done. Deployed to testnet. I'll close this after deploying to staging and prod (mainnet)

**Comment by wpdas** [comment]
Done
