### ISSUE TITLE
Updated Flow

### ISSUE THREAD

**Issue by KriTiCal007** [PotLock/nadabot-app#38]
# Summary
The Get Check and verify flow is simplified

# Description
Check Figma the GET CHECK and VERIFY flow is distinguished and made more simpler...
https://www.figma.com/file/ckixqGfuRKZ63tTvdJzi6j/Potlock?type=design&node-id=4581-5614&mode=dev

# Acceptance Criteria

[List of criteria that must be met for the enhancement to be considered accepted]

# Additional Information

[Any other relevant information, such as links to related issues or pull requests]
![Uploading image.png…]()

**Comment by wpdas** [comment]
Done
