### ISSUE TITLE
Open The Pending Verify Notification if available on login

### ISSUE THREAD

**Issue by KriTiCal007** [PotLock/nadabot-app#39]
# Summary
Open The Pending Verify Notification if available on login

# Description
To make the verify checks more easy to access add a default notifaction for available to verify checks on notification. If already available make it popup on login.

# Acceptance Criteria

[List of criteria that must be met for the enhancement to be considered accepted]

# Additional Information

[Any other relevant information, such as links to related issues or pull requests]
<img width="436" alt="image" src="https://github.com/PotLock/nadabot-app/assets/56259533/6fa6c0f5-4e23-4fe4-888a-ee5b89510c1d">

**Comment by wpdas** [comment]
Done
