### ISSUE TITLE
[FEATURE] Create Testnet Version of application

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#4]
# Problem
Sybil providers need a way to test on testnet
# User Story(s):
 As a sybil provider, I want to test with my testnet contract, so that I can experiment with application

# Description
Testnet version of nadabot
# Acceptance Criteria

- [x] deploy to v1.nadabot.testnet
- [x] configure branch fo testnet 
- [x] configure testnet.nada.bot 
- [x] register in social
- [x] add to docs.nada.bot
- [x] also add fake sybil providers to this

# Limitations 
-
 # Resources
- outline links and relevant resources, references implementations

**Comment by wpdas** [comment]
Done
