### ISSUE TITLE
[ENHANCE] Pending Verication Stamps Also Showing up in Get Check Section

### ISSUE THREAD

**Issue by codingshot** [PotLock/nadabot-app#40]
Currently redundant, should no longer show up once in pending section
<img width="776" alt="" src="https://github.com/PotLock/nadabot-app/assets/45281667/cfba0b26-58e1-403c-9940-0d8ab2b4f175">

**Comment by wpdas** [comment]
@codingshot I ain't able to reproduce this issue. Can you check this again, please?

**Comment by wpdas** [comment]
Closing because we can't reproduce this issue.
