### ISSUE TITLE
[BUG] Social Check Bug: Already Verified check shoowin up on get check

### ISSUE THREAD

**Issue by KriTiCal007** [PotLock/nadabot-app#65]
**Describe the bug**
Finised the Social Check got the points but the card is still showing to get check.

**To Reproduce**

**Expected behavior**
thecheck must not be on get check as I have social verification done

**Screenshots**
<img width="607" alt="image" src="https://github.com/PotLock/nadabot-app/assets/56259533/5459ab25-ac4b-4878-bff4-34d1a085edeb">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wpdas** [comment]
@KriTiCal007 those are different Cards/Providers. The one that you finished is using `has_complete_social_profile_check()` method. And the other one (with "Get Check" state) is using `has_complete_profile_check()`. They are two different providers.
